root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027EA8C61E50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027EA8CD3A00>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027EA8CCF490>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F935D22D30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F935D22190>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F935CB3D90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016D7538B460>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016D753AF490>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016D75467520>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D3F456DC10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000029423B1C1C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000029423AC4D00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000154B0B68520>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000154B0AB4910>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FF5343C1F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FF53435E20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - unsupported operand type(s) for +: 'NoneType' and 'list'
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002E10E661550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002E10E661970>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002E10E6C9400>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002E10E5EF940>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - 'NoneType' object is not iterable
root - WARNING - unsupported operand type(s) for +: 'NoneType' and 'list'
root - WARNING - object of type 'NoneType' has no len()
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CC94E03DF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CC94D37D90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - module 'slack' has no attribute 'WebClient'
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DB98595F10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DB9858B160>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - module 'slack' has no attribute 'WebClient'
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000151362DBBE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000151362053A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000154979E9D00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001549791FDC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - unsupported operand type(s) for +: 'NoneType' and 'list'
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015D9314A9D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015D9307F880>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B37E79BB80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B37E6C6340>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EB1221ADF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EB12151790>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002220B4ABB50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002220B3D6310>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002197D19AD90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002197D0D1820>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A5E4426190>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A5E4385400>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - module 'slack' has no attribute 'WebClient'
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F475303DF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F475230D60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F4751E45E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - HTTPConnectionPool(host='183.91.14.138', port=9000): Max retries exceeded with url: /clusters/Test/consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F475305E20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
root - WARNING - 'NoneType' object is not iterable
root - WARNING - unsupported operand type(s) for +: 'NoneType' and 'list'
root - WARNING - object of type 'NoneType' has no len()
